packages:
  - packages/*
  - packages/nuxt-openbao/playground
  - playground

minimumReleaseAge: 120
minimumReleaseAgeExclude:
  - "@chiballc/*"

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  unrs-resolver: true
